version: 2

updates:
  - package-ecosystem: composer
    cooldown:
      default-days: 7
    directory: /
    groups:
      composer:
        patterns:
          - "*"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    cooldown:
      default-days: 7
    directory: /
    groups:
      docker:
        patterns:
          - "*"
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: monthly

  - package-ecosystem: pre-commit
    cooldown:
      default-days: 7
    directory: /
    groups:
      hooks:
        patterns:
          - "*"
    schedule:
      interval: monthly
